
// Fix: Import Question type to be used in DEFAULT_QUESTION_BANK.
import { ExamConfig, Question } from './types';

export const ADMIN_ID = "Abir Hasan";
export const ADMIN_PASS = "25@bir85";

export const DEFAULT_EXAM_CONFIG: ExamConfig = {
  title: "সাইবার সিকিউরিটি পরীক্ষা",
  time: 10,
  totalMarks: 20,
  totalQuestions: 5,
  isActive: true,
  cutMarkPerWrongAnswer: 0.25,
  fixedPenalty: 1.5,
  correctAnswers: 'ABCDA',
};

// VAPID public key for web push notifications
// This would be generated by your backend in a real application
export const VAPID_PUBLIC_KEY = 'BDoY19p3k_Agq0GCI0bUT2A5EU5lviQYJc4aK_uH3hQ-S2qH5e_pRi2xqcI_3CqDxwODG8ggYqso_o7KGT4k1iU';


// Fix: Add default question bank to resolve missing import error.
export const DEFAULT_QUESTION_BANK: Question[] = [
  {
    id: 'q1',
    prompt: 'What does HTML stand for?',
    options: {
      A: 'Hyper Text Markup Language',
      B: 'High Tech Modern Language',
      C: 'Hyperlink and Text Markup Language',
      D: 'Home Tool Markup Language'
    },
    correctAnswer: 'A'
  },
  {
    id: 'q2',
    prompt: 'Which tag is used to create a hyperlink?',
    options: {
      A: '<link>',
      B: '<a>',
      C: '<href>',
      D: '<p>'
    },
    correctAnswer: 'B'
  },
  {
    id: 'q3',
    prompt: 'What does CSS stand for?',
    options: {
      A: 'Creative Style Sheets',
      B: 'Computer Style Sheets',
      C: 'Cascading Style Sheets',
      D: 'Colorful Style Sheets'
    },
    correctAnswer: 'C'
  },
  {
    id: 'q4',
    prompt: 'Which property is used to change the background color?',
    options: {
      A: 'color',
      B: 'bgcolor',
      C: 'background',
      D: 'background-color'
    },
    correctAnswer: 'D'
  },
  {
    id: 'q5',
    prompt: 'Which is a JavaScript framework?',
    options: {
      A: 'React',
      B: 'Laravel',
      C: 'Django',
      D: 'Sass'
    },
    correctAnswer: 'A'
  }
];